version: 2
updates:
  - package-ecosystem: "npm" # Change this based on your project (e.g., "pip" for Python)
    directory: "/" 
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
